CREATE TABLE IF NOT EXISTS tagihan_pln (
    nama_file TEXT,
    thbl DATE,
    no_rekening TEXT,
    id_pelanggan TEXT,
    nama_pelanggan TEXT,
    alamat_pelanggan TEXT,
    nama_npwp TEXT,
    alamat_npwp TEXT,
    status TEXT,
    golongan_tarif TEXT,
    faktor_kali_meter TEXT,
    nik TEXT,
    subsidi TEXT,
    kwh_lwbp NUMERIC,
    kwh_wbp NUMERIC,
    kvarh NUMERIC,
    tarif_lwbp NUMERIC,
    tarif_wbp NUMERIC,
    tarif_kvarh NUMERIC,
    jatuh_tempo DATE,
    tunggakan_sebelumnya NUMERIC,
    biaya_penyambungan NUMERIC,
    ujl NUMERIC,
    angsuran_lain NUMERIC,
    biaya_beban NUMERIC,
    total_tagihan NUMERIC,
    rupiah_terpakai NUMERIC,
    rupiah_kompensasi NUMERIC,
    rupiah_setelah_kompensasi NUMERIC,
    dpp NUMERIC,
    ppn NUMERIC,
    pbjt NUMERIC,
    jasa_layanan NUMERIC,
    rec NUMERIC,
    ppn_rec NUMERIC,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
